language: minimal
services:
- docker
jobs:
  include:
  - stage: build
    script:
    - cd src
    - docker run --rm -it -v "$PWD":/app -w /app composer install
    - docker run --rm -it -v "$PWD":/app -w /app node:lts npm install
    - docker run --rm -it -v "$PWD":/app -w /app node:lts npm run compile:css
  - stage: deploy
    addons:
      ssh_known_hosts:
      - "$PRODUCTION_SERVER"
    branches:
      only:
      - master
    before_script:
      - which ssh-agent || ( apt update -y && apt install -y openssh-client )
      - eval $(ssh-agent -s)
      - openssl aes-256-cbc -K $encrypted_e6cc0fb2b8da_key -iv $encrypted_e6cc0fb2b8da_iv -in production_deploy_key.enc -out production_deploy_key -d
      - chmod 600 production_deploy_key
      - ssh-add production_deploy_key
      - echo -e "Host $PRODUCTION_SERVERntStrictHostKeyChecking non" >> ~/.ssh/config

    script:
      - ssh $PRODUCTION_USER@$PRODUCTION_SERVER "/bin/bash -s " < production_deploy.sh
