language: minimal

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - cd src
        - docker run --rm -it -v "$PWD":/app -w /app composer install
        - docker run --rm -it -v "$PWD":/app -w /app node:lts npm install
        - docker run --rm -it -v "$PWD":/app -w /app node:lts npm run compile:css
    - stage: deploy
      addons:
        ssh_known_hosts:
          - $PRODUCTION_SERVER
      branches:
        only:
          - master
      before_script:
        - echo -e "Host $PRODUCTION_SERVERntStrictHostKeyChecking non" >> ~/.ssh/config
        - 'which ssh-agent || ( apt update -y && apt install -y openssh-client )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$PRODUCTION_SSH_PRIVATE" | ssh-add -
      script:
        - ssh $PRODUCTION_USER@$PRODUCTION_SERVER "/bin/bash -s " < "cd /home/ubuntu/wordpress && touch flag"
