language: minimal

services:
  - docker

jobs:
  include:
    - stage: composer
      script:
        - docker run --rm -it -v "$PWD":/app -w /app composer install
        - docker run --rm -it -v "$PWD":/usr/src/app -w /usr/src/app node:lts npm install
