language: minimal

services:
  - docker

before_script: cd src

jobs:
  include:
    - stage: build
      script:
        - docker run --rm -it -v "$PWD":/app -w /app composer install
        - docker run --rm -it -v "$PWD":/app -w /app node:lts npm install
